# Generated by Django 5.2.7 on 2025-12-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
