# Generated by Django 5.2.7 on 2025-10-30 14:47

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("full_name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500, null=True)),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                (
                    "national_code",
                    models.CharField(max_length=10, null=True, unique=True),
                ),
                ("birthday_date", django_jalali.db.models.jDateField(null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("last_login", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OTPCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=11, unique=True)),
                ("code", models.CharField(max_length=6)),
                ("created", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
