# Generated by Django 5.2.7 on 2025-11-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday_date",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
