# Generated by Django 5.2.7 on 2025-10-22 20:52

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
