# Generated by Django 5.2.7 on 2026-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.DecimalField(decimal_places=14, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.DecimalField(decimal_places=14, max_digits=40, null=True),
        ),
    ]
