# Generated by Django 5.2.7 on 2026-06-01 09:52

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_article_created_at_alter_article_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=blog.models.article_image_path),
        ),
    ]
