# Generated by Django 5.2.7 on 2025-12-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="price",
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
