# Generated by Django 5.2.7 on 2025-12-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="price",
            new_name="sum_of_price",
        ),
    ]
