# Generated by Django 5.2.7 on 2025-12-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_rename_price_cartitem_sum_of_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="sum_of_price",
            new_name="total_price",
        ),
    ]
