# Generated by Django 5.2.7 on 2025-12-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_rename_sum_of_price_cartitem_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
