# Generated by Django 5.2.7 on 2025-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cart_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="total_price",
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
