# Generated by Django 5.2.7 on 2025-11-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="Slide/")),
            ],
            options={
                "verbose_name": "Slide Image",
                "verbose_name_plural": "Slide Images",
            },
        ),
    ]
